package com.zt.lock;

import java.util.ArrayList;
import java.util.List;

public class AddToList implements Runnable {
	int startnum = 0;
	public static List<Integer> numberList = new ArrayList<Integer>();

	public AddToList(int startnumber) {
		startnum = startnumber;
	}

	@Override
	public void run() {
		int count = 0;
		while (count < 1000000) {
			numberList.add(startnum);
			startnum += 2;
			count++;
		}
	}
	
	public static void main(String[] args) throws InterruptedException {
		Thread t1 = new Thread(new AddToList(0));
		Thread t2 = new Thread(new AddToList(1));
		t1.start();
		t2.start();
		while (t1.isAlive() || t2.isAlive()) {
			Thread.sleep(1);
		}
		System.out.println(numberList.size());
	}

}

/**
       代码运行结果：
    Exception in thread "Thread-0" java.lang.ArrayIndexOutOfBoundsException: 1234
	at java.util.ArrayList.add(ArrayList.java:463)
	at com.zt.lock.AddToList.run(AddToList.java:18)
	at java.lang.Thread.run(Thread.java:748)
	
	分析：
	根据结果可以，ArrayIndexOutOfBoundsException越界了，按道理ArrayList应该自动扩展，怎么会越界呢？
	并且最后的总数不是200万
	
	因为：
	其中一个线程在执行中停止了，另外一个线程已经执行完毕了
 * 
 * 
 */
